import os
import smtplib
import feedparser
import google.generativeai as genai
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header
from datetime import datetime

# 1. 获取环境变量
GEMINI_KEY = os.environ.get("GEMINI_API_KEY")
GMAIL_USER = os.environ.get("GMAIL_USER")
GMAIL_PASSWORD = os.environ.get("GMAIL_PASSWORD")
TO_EMAIL = GMAIL_USER 

# 这里我换了一个更稳定的雅虎财经 RSS 源
RSS_URL = "https://finance.yahoo.com/news/rssindex"

def get_latest_news():
    print("正在抓取最新财经新闻...")
    feed = feedparser.parse(RSS_URL)
    news_items = []
    
    # 只取前 8 条
    for entry in feed.entries[:8]:
        # --- 修复核心：更安全的字段获取方式 ---
        # 尝试获取 summary，如果没有就获取 description，还没有就显示“暂无详情”
        # getattr(对象, '属性名', '默认值') 是 Python 防止报错的写法
        title = getattr(entry, 'title', '无标题')
        summary = getattr(entry, 'summary', getattr(entry, 'description', '暂无详细内容'))
        
        # 组合起来
        news_items.append(f"- 标题: {title}\n  简介: {summary}")
        
    return "\n".join(news_items)

def get_ai_report(news_data):
    print("正在让 Gemini 撰写分析报告...")
    genai.configure(api_key=GEMINI_KEY)
    model = genai.GenerativeModel('gemini-pro-latest')
    
    today = datetime.now().strftime("%Y-%m-%d")
    
    prompt = f"""
    你是一位资深的华尔街财经分析师。请根据以下抓取到的最新财经新闻，为我撰写一份【{today} 全球经济早报】。
    
    【新闻数据】：
    {news_data}
    
    【撰写要求】：
    1. 风格：专业、简洁、客观，类似彭博社简报。
    2. 结构：
       - 🌍 **市场综述**：用一句话总结当前市场情绪。
       - 🚀 **重点关注**：从新闻中挑出 3 个最重要的事件进行深度解读。
       - 📉 **风险提示**：潜在的风险点。
    3. 格式：**必须直接输出 HTML 代码**，不要包含 markdown 标记（如 ```html）。
       - 使用 <h2> 修饰小标题，颜色使用深蓝色。
       - 使用 <ul> 和 <li> 列出要点。
       - 重点词汇用 <b> 加粗。
       - 结尾加上一句：“Generated by Gemini AI”.
    """
    
    try:
        response = model.generate_content(prompt)
        # 清理可能残留的 markdown 标记
        return response.text.replace("```html", "").replace("```", "")
    except Exception as e:
        return f"<p>AI 生成报告失败: {str(e)}</p>"

def send_email(html_content):
    print("正在发送邮件...")
    msg = MIMEMultipart()
    subject_date = datetime.now().strftime("%m月%d日")
    msg['From'] = Header(f"Gemini Analyst <{GMAIL_USER}>", 'utf-8')
    msg['To'] = Header("Boss", 'utf-8')
    msg['Subject'] = Header(f"📊 每日经济早报 ({subject_date})", 'utf-8')
    
    msg.attach(MIMEText(html_content, 'html', 'utf-8'))
    
    try:
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(GMAIL_USER, GMAIL_PASSWORD)
        server.sendmail(GMAIL_USER, [TO_EMAIL], msg.as_string())
        server.quit()
        print("✅ 邮件发送成功！")
    except Exception as e:
        print(f"❌ 发送失败: {e}")

if __name__ == "__main__":
    if not GEMINI_KEY:
        print("❌ 缺少 API Key，请检查 Secrets 设置")
    else:
        try:
            raw_news = get_latest_news()
            # 只有抓取到新闻才继续
            if raw_news:
                report = get_ai_report(raw_news)
                send_email(report)
            else:
                print("⚠️ 未抓取到新闻数据")
        except Exception as e:
            print(f"❌ 运行过程中发生错误: {e}")
